### ISSUE TITLE
database field names with underscores

### ISSUE THREAD

**Issue by mbucc** [kristapsdz/kwebapp#4]
Hi Kristaps,

This config fails to build:
```
struct gig {
  field gig_id int;
};
```
with the error: 
```
$ kwebapp-c-header <t.conf
kwebapp-c-header: <stdin>:2:12: unknown input token
kwebapp-c-header: <stdin>:2:12: expected field type
$
```

If I remove the underscore, it works fine.  Are underscores allowed in field names?

**Comment by kristapsdz** [comment]
From the manpage:

```
Objects are generally named by an identifier.  These are always case-
insensitive alphanumeric non-empty string beginning with a letter.  There
are many disallowed or reserved identifiers.  There are also unique name
constraints to consider (e.g., no two structures can have the same name,
etc.).
```

The reason I disallow all but alphanumerics is because I need to uniquely recombine names when creating functions.  For example, I might create the C variable `has_foo`.  It's easier to disallow the underscore than always detect whether it's prefixed by `has_`.

Yes, this is a little heavyweight---but I figured I'd start restrictive, then open things up as I understand the system better later!

**Comment by mbucc** [comment]
Sorry I missed that in the man page; I changed my fields to remove underscores.

BTW, I also had a field called date, which sqlite3 require you to put in quotes, which also is not supported.  But that's not the smartest field name.  ;)
